Repository Gannies/Gannies_FrontEnd, pull requests merged in 2024-09, with the labels that each got.

#53 Refactor/#52 admin page separation
  src/hooks/useEventHandler.js
  src/layouts/index.jsx
  src/pages/Admin/AdminSideTab/index.jsx
  src/pages/Admin/AdminSideTab/style.js
  src/pages/Admin/MemberManagement/index.jsx
  src/pages/Admin/PaginationWrapper/index.jsx
  src/pages/Admin/PostManagement/index.jsx
  src/pages/Admin/ReportHistory/index.jsx
  src/pages/Admin/TableDesign/TableBodyRow/index.jsx
  src/pages/Admin/UserApproval/index.jsx
  src/pages/Admin/data.js
  src/pages/Admin/index.jsx
  src/pages/Admin/style.js
  src/routes/router.jsx
  src/styles/commonStyle/text.js
Labels: ✨feat, ♻️refactor

#56 Refactor/#54 my page separation
  src/hooks/useEventHandler.js
  src/layouts/index.jsx
  src/layouts/style.js
  src/pages/Admin/AdminSideTab/index.jsx
  src/pages/MyPage/MyPageSideTab/data.js
  src/pages/MyPage/MyPageSideTab/index.jsx
  src/pages/MyPage/MyPageSideTab/style.js
  src/pages/MyPage/PasswordChange/index.jsx
  src/pages/MyPage/PasswordChange/style.js
  src/pages/MyPage/PersonalInfo/index.jsx
  src/pages/MyPage/PersonalInfo/style.js
  src/pages/MyPage/PostContents/index.jsx
  src/pages/MyPage/PostContents/style.js
  src/pages/MyPage/ScrappedPost/index.jsx
  src/pages/MyPage/ScrappedPost/style.js
  src/pages/MyPage/SideTabMenu/index.jsx
  src/pages/MyPage/WrittenComment/index.jsx
  src/pages/MyPage/WrittenComment/style.js
  src/pages/MyPage/WrittenPost/index.jsx
  src/pages/MyPage/WrittenPost/style.js
  src/pages/MyPage/data.js
  src/pages/MyPage/index.jsx
  src/pages/MyPage/style.js
  src/routes/router.jsx
Labels: ✨feat, ♻️refactor

#59 Style/#55 post detail page layout
  src/assets/icons/etc/comment_reply.svg
  src/components/Icons/Clock/index.jsx
  src/components/Icons/Eye/index.jsx
  src/components/Icons/Message/index.jsx
  src/components/Icons/More/index.jsx
  src/components/Pagination/index.jsx
  src/components/PostList/index.jsx
  src/pages/Admin/MemberManagement/index.jsx
  src/pages/Admin/PostManagement/index.jsx
  src/pages/Admin/ReportHistory/index.jsx
  src/pages/Admin/UserApproval/index.jsx
  src/pages/Community/CommunityPost/index.jsx
  src/pages/Community/index.jsx
  src/pages/MyPage/ScrappedPost/index.jsx
  src/pages/MyPage/WrittenComment/index.jsx
  src/pages/MyPage/WrittenPost/index.jsx
  src/pages/PostDetail/CommentCreate/index.jsx
  src/pages/PostDetail/CommentCreate/style.js
  src/pages/PostDetail/MorePopup/index.jsx
  src/pages/PostDetail/MorePopup/style.js
  src/pages/PostDetail/OtherPostList/index.jsx
  src/pages/PostDetail/OtherPostList/style.js
  src/pages/PostDetail/OtherPosts/index.jsx
  src/pages/PostDetail/OtherPosts/style.js
  src/pages/PostDetail/PostCommentArea/PostCommentList/index.jsx
  src/pages/PostDetail/PostCommentArea/PostCommentList/style.js
  src/pages/PostDetail/PostCommentArea/index.jsx
  src/pages/PostDetail/PostHeader/PostInfo/index.jsx
  src/pages/PostDetail/PostHeader/PostTitleSection/index.jsx
  src/pages/PostDetail/PostHeader/PostTitleSection/style.js
  src/pages/PostDetail/index.jsx
  src/pages/PostDetail/style.js
  src/routes/router.jsx
Labels: ✨feat, 🎨style

#63 Chore/#60 env create and axios settings and api fnc settings
  .env.development
  .gitignore
  package-lock.json
  package.json
  src/api/adminApi.js
  src/api/authApi.js
  src/api/axiosInstance.js
  src/api/commentApi.js
  src/api/hospitalSearchApi.js
  src/api/likeApi.js
  src/api/postApi.js
  src/api/reportApi.js
  src/api/scrapApi.js
  src/api/userApi.js
Labels: 🔨chore

#65 Feat/#62 mypage feat
  .gitignore
  src/api/authApi.js
  src/components/AlignSelectMenu/index.jsx
  src/hooks/useEventHandler.js
  src/hooks/useInputBorder.js
  src/pages/Find/ID/Inputs/Name/index.jsx
  src/pages/Find/ID/Inputs/PhoneNumber/index.jsx
  src/pages/Find/ID/Inputs/VerifyNumber/index.jsx
  src/pages/Find/ID/index.jsx
  src/pages/Find/Password/Inputs/Email/index.jsx
  src/pages/Find/Password/index.jsx
  src/pages/MyPage/PasswordChange/index.jsx
  src/pages/MyPage/PasswordChange/style.js
  src/pages/MyPage/PersonalInfo/index.jsx
  src/pages/MyPage/PersonalInfo/style.js
  src/pages/MyPage/ScrappedPost/index.jsx
  src/pages/MyPage/WrittenComment/index.jsx
  src/pages/MyPage/WrittenPost/index.jsx
  src/pages/SignIn/Inputs/index.jsx
  src/pages/SignIn/Inputs/style.js
  src/pages/SignUp/Department/index.jsx
  src/pages/SignUp/Identity/Inputs/Name/index.jsx
  src/pages/SignUp/Identity/Inputs/PhoneNumber/index.jsx
  src/pages/SignUp/Identity/Inputs/PhoneNumber/style.js
  src/pages/SignUp/Identity/Inputs/VerifyNumber/index.jsx
  src/pages/SignUp/Identity/Inputs/VerifyNumber/style.js
  src/pages/SignUp/Identity/index.jsx
  src/pages/SignUp/Info/Inputs/Email/index.jsx
  src/pages/SignUp/Info/Inputs/Nickname/index.jsx
  src/pages/SignUp/Info/Inputs/Password/index.jsx
  src/pages/SignUp/Info/Inputs/Password/style.js
  src/pages/SignUp/Info/Inputs/PasswordCheck/index.jsx
  src/pages/SignUp/Info/Inputs/index.jsx
  src/pages/SignUp/components/DefaultInput/index.jsx
  src/pages/SignUp/components/DefaultInput/style.js
  src/styles/commonStyle/input.js
Labels: ✨feat, 🎨style

#67 Feat/#64 community page
  package-lock.json
  package.json
  src/api/authApi.js
  src/components/CommunityBannerText/index.jsx
  src/hooks/useEventHandler.js
  src/hooks/useSelectorList.js
  src/layouts/Navbar/data.js
  src/layouts/Navbar/index.jsx
  src/layouts/Navbar/style.js
  src/layouts/header/index.jsx
  src/layouts/header/style.js
  src/main.jsx
  src/pages/Admin/AdminSideTab/index.jsx
  src/pages/Admin/MemberManagement/index.jsx
  src/pages/Admin/PostManagement/index.jsx
  src/pages/Admin/ReportHistory/index.jsx
  src/pages/Admin/UserApproval/index.jsx
  src/pages/Community/CommunityPost/index.jsx
  src/pages/Community/CommunityPost/style.js
  src/pages/Community/index.jsx
  src/pages/Community/style.js
  src/pages/CreateCommunityPost/Buttons/index.jsx
  src/pages/CreateCommunityPost/PostCreateEditor/index.jsx
  src/pages/CreateCommunityPost/index.jsx
  src/pages/CreateCommunityPost/style.js
  src/pages/Home/index.jsx
  src/pages/MyPage/MyPageSideTab/index.jsx
  src/pages/MyPage/ScrappedPost/index.jsx
  src/pages/MyPage/WrittenComment/index.jsx
  src/pages/MyPage/WrittenPost/index.jsx
  src/pages/PostDetail/index.jsx
  src/store/communityData.js
  src/store/navBarOptions.js
  src/store/store.js
Labels: ✨feat

#72 Feat/#70 공용 페이지네이션 기능 완성
  src/api/adminApi.js
  src/api/dataCountApi.js
  src/api/hospitalSearchApi.js
  src/api/postApi.js
  src/api/reportApi.js
  src/api/userApi.js
  src/components/Icons/Clock/index.jsx
  src/components/Icons/Eye/index.jsx
  src/components/Icons/style.js
  src/components/PageNumber/index.jsx
  src/components/Pagination/index.jsx
  src/hooks/useFetchAndPaginate.js
  src/pages/Community/CommunityPost/index.jsx
  src/pages/Community/CommunityPost/style.js
  src/pages/Community/index.jsx
  src/styles/commonStyle/wrapper.js
  src/utils/dateFormatting/index.js
  src/utils/itemLimit/index.js
Labels: ✨feat

#73 Feat/#70 enhance community pages
  src/App.jsx
  src/api/authApi.js
  src/assets/images/loading_circle.gif
  src/components/AlignSelectMenu/index.jsx
  src/components/LoadingCircle/index.jsx
  src/components/PageCategory/index.jsx
  src/hooks/useEventHandler.js
  src/hooks/useFetchAndPaginate.js
  src/hooks/useLoginCheck.js
  src/hooks/useSelectorList.js
  src/layouts/header/index.jsx
  src/pages/Admin/AdminSideTab/index.jsx
  src/pages/Admin/MemberManagement/index.jsx
  src/pages/Admin/PostManagement/index.jsx
  src/pages/Admin/ReportHistory/index.jsx
  src/pages/Admin/UserApproval/index.jsx
  src/pages/Community/data.js
  src/pages/Community/index.jsx
  src/pages/Community/style.js
  src/pages/CreateCommunityPost/index.jsx
  src/pages/MyPage/MyPageSideTab/index.jsx
  src/pages/MyPage/PasswordChange/index.jsx
  src/pages/MyPage/ScrappedPost/index.jsx
  src/pages/MyPage/WrittenComment/index.jsx
  src/pages/MyPage/WrittenPost/index.jsx
  src/pages/PostDetail/index.jsx
  src/pages/SignIn/Buttons/index.jsx
  src/pages/SignIn/index.jsx
  src/routes/router.jsx
  src/store/auth.js
  src/store/communityData.js
  src/store/store.js
  src/utils/dateFormatting/index.js
Labels: ✨feat, ♻️refactor, 🎨style
