Repository Gannies/Gannies_FrontEnd, pull requests merged in 2024-11, with the labels that each got.

#104 Feat/#91 page and api enhancements
  package-lock.json
  package.json
  src/api/authApi.js
  src/assets/icons/etc/file.svg
  src/assets/images/not_image.jpg
  src/components/AlignSelectMenu/data.js
  src/components/Loading/EditorLoadingCircle/index.jsx
  src/hooks/useModalsControl.js
  src/hooks/useSelectorList.js
  src/hooks/useTinyMceImageUpload.js
  src/hooks/useTinyMceUpload.js
  src/pages/Admin/AdminSideTab/index.jsx
  src/pages/Admin/AdminSideTab/style.js
  src/pages/Admin/AdminSignIn/index.jsx
  src/pages/Admin/MemberManagement/index.jsx
  src/pages/Admin/MemberManagement/style.js
  src/pages/Admin/Modals/MemberManagementModal/index.jsx
  src/pages/Admin/Modals/MemberManagementModal/style.js
  src/pages/Admin/PostsAndCommentsManageMent/index.jsx
  src/pages/Admin/ReportHistory/index.jsx
  src/pages/Admin/ReportHistory/style.js
  src/pages/Admin/UserApproval/index.jsx
  src/pages/Community/CommunityPost/index.jsx
  src/pages/Community/index.jsx
  src/pages/Community/style.js
  src/pages/CreateCommunityPost/PostCreateEditor/UploadFileList/OptionsList/index.jsx
  src/pages/CreateCommunityPost/PostCreateEditor/UploadFileList/index.jsx
  src/pages/CreateCommunityPost/PostCreateEditor/UploadFileList/style.js
  src/pages/CreateCommunityPost/PostCreateEditor/index.jsx
  src/pages/CreateCommunityPost/PostCreateEditor/style.js
  src/pages/CreateCommunityPost/index.jsx
  src/pages/MyPage/PostContents/index.jsx
  src/pages/PostDetail/OtherPosts/index.jsx
  src/pages/PostDetail/PostCommentArea/PostCommentList/index.jsx
  src/pages/PostDetail/PostHeader/Attachments/index.jsx
  src/pages/PostDetail/PostHeader/Attachments/style.js
  src/pages/PostDetail/PostHeader/PostInfo/index.jsx
  src/pages/PostDetail/PostHeader/PostTitleSection/style.js
  src/pages/PostDetail/index.jsx
  src/store/modalsControl.js
  src/styles/GlobalStyle.js
  src/styles/commonStyle/etc.js
  src/utils/dateFormatting/index.js
Labels: 🐛fix, ✨feat, ♻️refactor, 🎨style

#105 Feat/#101: Login logic and other error fixes
  README.md
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/api/authApi.js
  src/api/socketAPI.js
  src/api/userApi.js
  src/components/AlignSelectMenu/data.js
  src/components/Modal/ExtendSession/index.jsx
  src/components/Modal/index.jsx
  src/components/Modal/style.js
  src/components/PostList/index.jsx
  src/hooks/useLoginCheck.js
  src/hooks/useSelectorList.js
  src/hooks/useSocket.js
  src/layouts/Header/index.jsx
  src/pages/Find/Password/index.jsx
  src/pages/Home/Link/index.jsx
  src/pages/MyPage/ScrappedPost/index.jsx
  src/pages/MyPage/WrittenComment/index.jsx
  src/pages/MyPage/WrittenPost/index.jsx
  src/pages/PostDetail/index.jsx
  src/pages/SignIn/Buttons/index.jsx
  src/pages/SignIn/Inputs/index.jsx
  src/pages/SignIn/index.jsx
  src/pages/SignUp/Department/index.jsx
  src/store/modalState.js
  src/utils/socket/index.js
  vite.config.js
Labels: 🐛fix, ✨feat, 🎨style

#107 Feat/#91 page and api enhancements
  README.md
  index.html
  public/logo.png
  src/hooks/useTinyMceUpload.js
  src/pages/Admin/MemberManagement/index.jsx
  src/pages/Admin/PostsAndCommentsManageMent/index.jsx
  src/pages/Admin/SearchInput/index.jsx
Labels: ✨feat, 🎨style

#109 Feat/#108 main page and header search bar debounce
  README.md
  src/hooks/usePostSearch.js
Labels: ✨feat

#112 Fix/#111 bug fix branch
  src/hooks/useTinyMceUpload.js
  src/pages/CreateCommunityPost/HospitalSearchModal/KakaoMap/index.jsx
  src/pages/CreateCommunityPost/PostCreateEditor/index.jsx
  src/pages/CreateCommunityPost/PostCreateEditor/style.js
  src/pages/CreateCommunityPost/index.jsx
  src/pages/PostDetail/index.jsx
  src/pages/PostDetail/style.js
  src/styles/GlobalStyle.js
  src/styles/commonStyle/etc.js
Labels: 🐛fix, ✨feat

#113 Fix/#111 bug fix branch
  src/api/userApi.js
  src/hooks/useTinyMceUpload.js
  src/pages/Admin/PostsAndCommentsManageMent/index.jsx
  src/pages/CreateCommunityPost/PostCreateEditor/index.jsx
  src/pages/CreateCommunityPost/index.jsx
  src/pages/MyPage/MyPageSideTab/index.jsx
  src/pages/PostDetail/index.jsx
  src/pages/PostDetail/style.js
Labels: 🐛fix, ♻️refactor

#114 Fix/#111 bug fix branch
  src/components/AlignSelectMenu/index.jsx
  src/pages/Admin/ReportHistory/index.jsx
  src/pages/Admin/SearchInput/index.jsx
  src/pages/Community/index.jsx
  src/pages/Community/style.js
Labels: 🐛fix

#115 [🐛fix]: #111 export 표기 오류 수정
  src/pages/Community/style.js
Labels: 🐛fix

#116 Update README.md
  README.md
Labels: 📝docs

#117 [🐛fix]: #111 메인 페이지 UI 오류 수정
  src/App.jsx
  src/hooks/useSocket.js
  src/pages/Home/Link/index.jsx
  src/pages/Home/Posts/data.js
Labels: 🐛fix

#118 [🐛fix]: #111 [community] 검색 시 표기되는 카테고리 select UI 보이는 오류 수정
  src/pages/Community/index.jsx
Labels: 🐛fix

#119 [✨feat]: #111 정지 해제 시 이메일 발송 추가
  src/api/adminApi.js
  src/pages/Admin/MemberManagement/index.jsx
Labels: ✨feat
